// fittrak-react/src/components/WorkoutList.js
import React from "react";

import { Query } from "react-apollo";

import WorkoutCard from "./WorkoutCard";
import queries from "../graphql/queries";

class WorkoutList extends React.Component {
  render() {
    return (
      <Query query={queries.workoutsQuery}>
        {({ loading, error, data }) => {
          if (loading) return "Loading workouts ...";
          if (error) return "Error loading workouts";

          return data.workouts.map(workout => {
            return <WorkoutCard key={workout.id} workout={workout} />;
          });
        }}
      </Query>
    );
  }
}

export default WorkoutList;

// fittrak-client/src/components/WorkoutList.vue
<template>
  <div>
    <h2>{{ title }}</h2>
    <p v-if="activeWorkouts.length">
      <ul>
        <WorkoutItem
         v-for="workout in activeWorkouts"
          :key="workout.id"
          :workout="workout"
          />
      </ul>
    </p>
    <p v-else>
      No workouts!
    </p>
  </div>
</template>

<script>
import WorkoutItem from "./WorkoutItem";

import WORKOUTS from "@/graphql/queries/workouts.graphql";

export default {
  name: "WorkoutList",

  data() {
    return {
      workouts: []
    };
  },

  apollo: {
    workouts: {
      query: WORKOUTS,
      update: data => data.viewer.workouts
    }
  },

  computed: {
    activeWorkouts() {
      return this.workouts.filter(workout => workout.isActive);
    }
  },

  components: {
    WorkoutItem
  },

  props: {
    title: String
  }
};
</script>
